version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: ./mynotes
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./mynotes:/app
